export * from './auth';
export * from './layout';
export * from './tariffs';
export * from './accounts';
export * from './places';
export * from './clients';
export * from './client';
export * from './prepare';
export * from './entry';

// --------- PREPARE

export const PREPARE_GET_REQUEST = '[PREPARE] GET_REQUEST';
export const PREPARE_GET_SUCCESS = '[PREPARE] GET_SUCCESS';
export const PREPARE_GET_FAILURE = '[PREPARE] GET_FAILURE';
export const PREPARE_GET_CANCELED = '[PREPARE] GET_CANCELED';

// --------- LAYOUT

export const LAYOUT_SHOW_SIDEBAR = '[LAYOUT] SHOW_SIDEBAR';
export const LAYOUT_HIDE_SIDEBAR = '[LAYOUT] HIDE_SIDEBAR';

export const ADD_NOTIFICATION_APP_SETTING = '[LAYOUT] ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION_APP_SETTING = '[LAYOUT] REMOVE_NOTIFICATION';

// --------- AUTH

export const AUTH_SIGN_IN_REQUEST = '[AUTH] SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = '[AUTH] SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = '[AUTH] SIGN_IN_FAILURE';
export const AUTH_SIGN_IN_CANCELED = '[AUTH] SIGN_IN_CANCELED';
export const AUTH_USER_SET = '[AUTH] USER_SET';

export const AUTH_SIGN_OUT_REQUEST = '[AUTH] SIGN_OUT_REQUEST';
export const AUTH_SIGN_OUT_SUCCESS = '[AUTH] SIGN_OUT_SUCCESS';
export const AUTH_SIGN_OUT_FAILURE = '[AUTH] SIGN_OUT_FAILURE';

// --------- CLIENTS

export const CLIENTS_GET_LIST_REQUEST = '[CLIENTS] GET_LIST_REQUEST';
export const CLIENTS_GET_LIST_SUCCESS = '[CLIENTS] GET_LIST_SUCCESS';
export const CLIENTS_GET_LIST_FAILURE = '[CLIENTS] GET_LIST_FAILURE';
export const CLIENTS_GET_LIST_CANCELED = '[CLIENTS] GET_LIST_CANCELED';
export const CLIENTS_SET_CURRENT_CLIENT_ID = '[CLIENTS] SET_CURRENT_CLIENT_ID';
export const CLIENTS_SET_SORT_BY = '[CLIENTS] SET_SORT_BY';
export const CLIENTS_SET_SEARCH_STRING = '[CLIENTS] SET_SEARCH_STRING';

// --------- CLIENT

export const CLIENT_ADD_NEW_REQUEST = '[CLIENT] POST_ADD_NEW_REQUEST';
export const CLIENT_ADD_NEW_SUCCESS = '[CLIENT] POST_ADD_NEW_SUCCESS';
export const CLIENT_ADD_NEW_FAILURE = '[CLIENT] POST_ADD_NEW_FAILURE';
export const CLIENT_ADD_NEW_CANCELED = '[CLIENT] POST_ADD_NEW_CANCELED';

export const CLIENT_PUT_ITEM_REQUEST = '[CLIENT] PUT_ITEM_REQUEST';
export const CLIENT_PUT_ITEM_SUCCESS = '[CLIENT] PUT_ITEM_SUCCESS';
export const CLIENT_PUT_ITEM_FAILURE = '[CLIENT] PUT_ITEM_FAILURE';
export const CLIENT_PUT_ITEM_CANCELED = '[CLIENT] PUT_ITEM_CANCELED';

export const CLIENT_DELETE_ITEM_REQUEST = '[CLIENT] DELETE_ITEM_REQUEST';
export const CLIENT_DELETE_ITEM_SUCCESS = '[CLIENT] DELETE_ITEM_SUCCESS';
export const CLIENT_DELETE_ITEM_FAILURE = '[CLIENT] DELETE_ITEM_FAILURE';
export const CLIENT_DELETE_ITEM_CANCELED = '[CLIENT] DELETE_ITEM_CANCELED';

// --------- TARIFFS

export const TARIFFS_GET_LIST_REQUEST = '[TARIFFS] GET_LIST_REQUEST';
export const TARIFFS_GET_LIST_SUCCESS = '[TARIFFS] GET_LIST_SUCCESS';
export const TARIFFS_GET_LIST_FAILURE = '[TARIFFS] GET_LIST_FAILURE';
export const TARIFFS_GET_LIST_CANCELED = '[TARIFFS] GET_LIST_CANCELED';

// --------- ACCOUNTS

export const ACCOUNTS_GET_LIST_REQUEST = '[ACCOUNTS] GET_LIST_REQUEST';
export const ACCOUNTS_GET_LIST_SUCCESS = '[ACCOUNTS] GET_LIST_SUCCESS';
export const ACCOUNTS_GET_LIST_FAILURE = '[ACCOUNTS] GET_LIST_FAILURE';
export const ACCOUNTS_GET_LIST_CANCELED = '[ACCOUNTS] GET_LIST_CANCELED';
export const ACCOUNTS_LIST_SET_SORT_BY = '[ACCOUNTS] LIST_SET_SORT_BY';

// --------- ACCOUNT

export const ACCOUNT_GET_ITEM_REQUEST = '[ACCOUNT] GET_ITEM_REQUEST';
export const ACCOUNT_GET_ITEM_SUCCESS = '[ACCOUNT] GET_ITEM_SUCCESS';
export const ACCOUNT_GET_ITEM_FAILURE = '[ACCOUNT] GET_ITEM_FAILURE';
export const ACCOUNT_GET_ITEM_CANCELED = '[ACCOUNT] GET_ITEM_CANCELED';

export const ACCOUNT_ADD_NEW_REQUEST = '[ACCOUNT] POST_ADD_NEW_REQUEST';
export const ACCOUNT_ADD_NEW_SUCCESS = '[ACCOUNT] POST_ADD_NEW_SUCCESS';
export const ACCOUNT_ADD_NEW_FAILURE = '[ACCOUNT] POST_ADD_NEW_FAILURE';
export const ACCOUNT_ADD_NEW_CANCELED = '[ACCOUNT] POST_ADD_NEW_CANCELED';

export const ACCOUNT_PUT_ITEM_REQUEST = '[ACCOUNT] PUT_ITEM_REQUEST';
export const ACCOUNT_PUT_ITEM_SUCCESS = '[ACCOUNT] PUT_ITEM_SUCCESS';
export const ACCOUNT_PUT_ITEM_FAILURE = '[ACCOUNT] PUT_ITEM_FAILURE';
export const ACCOUNT_PUT_ITEM_CANCELED = '[ACCOUNT] PUT_ITEM_CANCELED';

export const ACCOUNT_DELETE_ITEM_REQUEST = '[ACCOUNT] DELETE_ITEM_REQUEST';
export const ACCOUNT_DELETE_ITEM_SUCCESS = '[ACCOUNT] DELETE_ITEM_SUCCESS';
export const ACCOUNT_DELETE_ITEM_FAILURE = '[ACCOUNT] DELETE_ITEM_FAILURE';
export const ACCOUNT_DELETE_ITEM_CANCELED = '[ACCOUNT] DELETE_ITEM_CANCELED';

// --------- PLACES

export const PLACES_GET_LIST_REQUEST = '[PLACES] GET_LIST_REQUEST';
export const PLACES_GET_LIST_SUCCESS = '[PLACES] GET_LIST_SUCCESS';
export const PLACES_GET_LIST_FAILURE = '[PLACES] GET_LIST_FAILURE';
export const PLACES_GET_LIST_CANCELED = '[PLACES] GET_LIST_CANCELED';
export const PLACES_SET_CURRENT_PLACE_ID = '[PLACES] SET_CURRENT_PLACE_ID';
export const PLACES_LIST_SET_SORT_BY = '[PLACES] LIST_SET_SORT_BY';

export const PLACES_ADD_NEW_REQUEST = '[PLACES] POST_ADD_NEW_REQUEST';
export const PLACES_ADD_NEW_SUCCESS = '[PLACES] POST_ADD_NEW_SUCCESS';
export const PLACES_ADD_NEW_FAILURE = '[PLACES] POST_ADD_NEW_FAILURE';
export const PLACES_ADD_NEW_CANCELED = '[PLACES] POST_ADD_NEW_CANCELED';

// --------- ENTRY

export const ENTRY_LINK_TO_PLACE_REQUEST = '[ENTRY] POST_LINK_TO_PLACE_REQUEST';
export const ENTRY_LINK_TO_PLACE_SUCCESS = '[ENTRY] POST_LINK_TO_PLACE_SUCCESS';
export const ENTRY_LINK_TO_PLACE_FAILURE = '[ENTRY] POST_LINK_TO_PLACE_FAILURE';
export const ENTRY_LINK_TO_PLACE_CANCELED = '[ENTRY] POST_LINK_TO_PLACE_CANCELED';

export const ENTRY_UNLINK_TO_PLACE_REQUEST = '[ENTRY] POST_UNLINK_TO_PLACE_REQUEST';
export const ENTRY_UNLINK_TO_PLACE_SUCCESS = '[ENTRY] POST_UNLINK_TO_PLACE_SUCCESS';
export const ENTRY_UNLINK_TO_PLACE_FAILURE = '[ENTRY] POST_UNLINK_TO_PLACE_FAILURE';
export const ENTRY_UNLINK_TO_PLACE_CANCELED = '[ENTRY] POST_UNLINK_TO_PLACE_CANCELED';
